### ISSUE TITLE
[bug] Enabling hardware acceleration freezes program

### ISSUE THREAD

**Issue by rambo919** [paulpacifico/shutter-encoder#119]
[sysinfo.txt](https://github.com/paulpacifico/shutter-encoder/files/10831132/sysinfo.txt)
![Screenshot_20230225_142906](https://user-images.githubusercontent.com/15326328/221356920-4955a8a1-7693-4096-94a9-9473f6256904.png)

Just enabling this (or trying to at least) with either 264 or 265 changes the mouse to the rolling ball and locks me out of the program and I need to use xkill to quit it.

Dunno if a dialog is supposed to appear?

Have tried both 16.5 and 16.8, both do it.

**Comment by paulpacifico** [comment]
Does encoding the file without the hardware acceleration works?

**Comment by paulpacifico** [comment]
Ok thanks, could you try to download a static build from here: https://johnvansickle.com/ffmpeg/
And replace the actual FFmpeg binaries from '**Library**' folder inside the Shutter Encoder app.

**Comment by rambo919** [comment]
Found the folder at "/usr/lib/Shutter Encoder/usr/bin/Library/"

Copied ffmpeg and ffprobe into it overriding.

Now it shows a dialog when I attempt to enable hardware acceleration:
"No hardware acceleration available. Make sure your drivers are up to date!"

It's the latest available drivers though. 520

**Comment by Augusto7743** [comment]
That bug happen because Shutter Enconder use internal ffmpeg to access nvenc library, but the OS not allow doing it.
In Ubuntu 20.04 the solution is :
- install ffmpeg latest version.
- run the commands

sudo rm "/usr/lib/Shutter Encoder/usr/bin/Library/"ffmpeg
sudo ln -s -v /usr/bin/ffmpeg "/usr/lib/Shutter Encoder/usr/bin/Library/"

**Comment by Augusto7743** [comment]
That bug happen because Shutter Enconder use internal ffmpeg to access nvenc library, but the OS not allow doing it.
In Ubuntu 20.04 the solution is :
- install ffmpeg latest version.
- run the commands

sudo rm "/usr/lib/Shutter Encoder/usr/bin/Library/"ffmpeg
sudo ln -s -v /usr/bin/ffmpeg "/usr/lib/Shutter Encoder/usr/bin/Library/"
