### ISSUE TITLE
App always fails to download update because it assumes wrong user folder

### ISSUE THREAD

**Issue by Majestic7979** [paulpacifico/shutter-encoder#133]
The app always fails to download updates because you hardcoded the save location.

You should user %userprofile%/Downloads on Windows 11 to ensure it downloads to the correct Download folder.

I have my "home" folder on a separate hard drive and I changed the location of my Windows Libraries to this location so whenever your app tries to download the update it fails as the folder it wants does not exist on the C: drive. Please fix, it's rather annoying to have to download manually every time because of the updating nagging (which I don't want to turn off because I want to be aware of the fixes and improvements).

By the way keep up the good work, I donated a couple of years ago because I really like your app!

**Comment by Majestic7979** [comment]
Hi @paulpacifico did you manage to take a look at this? Was posted on May 10th. Thanks.

**Comment by Majestic7979** [comment]
I reported this on May 10, some updates since then and still have this issue where your application has a hard-coded download target for updates. I even provided the solution above which is being ignored. As a financial supporter of the app I am very disappointed to have to open your website and click download then have to manually install every single time when you could just update your code to remove the hardcoded download folder and use a Temp folder or %userprofile% on Windows. It is a huge annoyance updating your app because of the error every time. I would like to see this fixed.

**Comment by Majestic7979** [comment]
@paulpacifico see above.

**Comment by paulpacifico** [comment]
Hi,

I'm sorry for not answering to you, honestly I've received so many mail/questions/post that I can't answer to everyone.
Moreover I'm not really improving this app for Linux because I'm not a Linux user and Windows/Mac OS are my priority.

However, I will check that for the next release (I promise) but it will be working for the v17.7 (because the v17.6 will be corrected).

Paul.

**Comment by Majestic7979** [comment]
It's for Windows, Paul... I am talking about Windows... when you coded the updater, you coded for it to download to a hardcoded folder on Windows which may not exist on every user's device.. case in point with me. You need to choose a folder that would be available on all devices, or you can use the variables instead, like %appdata% or %userprofile%. If you hardcode a destination then depending on the version of Windows it's not available and will always fail the download. It's an easy fix just don't know where in the source code you put the folder for the Windows updater. Thanks and I look forward to the fixed version in the near future.

**Comment by paulpacifico** [comment]
Sorry, It was late when I wrote the comment and I was very tired... I've changed the variable everything seems ok and ready for the next release.

Paul.

**Comment by DrSakuu** [comment]
I have moved my downloads folder away from %userprofile%/Downloads, so the downloads go in the wrong location. You should get the Downloads folder from registry `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders`, Downloads folder GUID is `{374DE290-123F-4565-9164-39C4925E467B}`

**Comment by paulpacifico** [comment]
The app is checking if the Downloads folder exists and if not fallback on the Desktop folder.

So I don't understand how it can fail, from which versions did you update before and after?

Paul.

**Comment by DrSakuu** [comment]
The download is not failing, it's going in the wrong location. I commented in this issue instead of making a new one, because this is where you  established the current behavior.

I am updating from 20.1 to 20.2. I have set my downloads folder to F:\Downloads, but Shutter Encoder does not use that location. See my %userprofile%(Sakuu-Holo)\Downloads on the left and my main downloads folder on the right. In the middle is the properties for the folder where I have changed the location (Sijainti).

<img width="1409" height="801" alt="Image" src="https://github.com/user-attachments/assets/a44f4345-d5e2-4a71-bb0a-2a373388a19d" />

You should read the downloads folder location from the registry as stated in my previous comment.
