### ISSUE TITLE
Add support for H266

### ISSUE THREAD

**Issue by IkelAtomig** [paulpacifico/shutter-encoder#211]
It is still being finalized on Hardware but for the software counterpart - https://github.com/ultravideo/uvg266

**Comment by paulpacifico** [comment]
It should be added for the v18.3 but I get compilation errors so I wasn't able to update FFmpeg. But everything is setup and ready for the v18.4.

Paul.

**Comment by IkelAtomig** [comment]
This shouldn't be asked here. But your silence on Linux platform support or issues is unacceptable. Please reply in the respective threads and delete this comment to keep this issue clean. If and only if you have replied there.

**Comment by paulpacifico** [comment]
Excuse me, but I'm developing this software for free since 2013 on every platforms. I have bought a Mac computer to make an Apple app, i've installed 3 differents distro and learn how to make it on Linux (because I never use Linux).
 
I'm the only one on the whole project including app, website, facebook, reddit, mails, github. But THIS IS NOT MY JOB, i'm a video editor and photographer i'm doing this on my free time.

I'm answering as fast and as possible as I can, but sometimes I don't know, I'm trying without responding because I DON'T HAVE THE TIME FOR!

So your answer is unacceptable, If you want something that does not exists, do like me, make it.

**Comment by IkelAtomig** [comment]
Your opinion is understandable. I get it, I am co-maintaining a free project too. We need to live IRL. Sorry, I should have used some good appropriate words. I actually commented it as a fact. But the way it seems was commented in a way of rage by myself. Apologies.

> If you want something that does not exists, do like me, make it.

I sure am gonna work on the Linux side of things and help you when I can and make PRs for it.

> I'm developing this software for free since 2013 on every platforms.

Thanks for the great project. Actually being a Windows user, it had good out of the box experience. Having switched to Linux doesn't seem so which kind of mildly infuriated myself.

> So your answer is unacceptable

Maybe or maybe not. I don't know what to comment on this.

---

Once again, apologies if my message was conveyed in a rash manner to you. I stated it as a fact without no hate in my mind.

---

Let's forget this and focus on making the app better. 😉

Sorry and Thanks at the same time.
