### ISSUE TITLE
Is the Web Download function now password protected?

### ISSUE THREAD

**Issue by ConnieVic** [paulpacifico/shutter-encoder#229]
It's been a while since I last used the web download function, but when I attempt to use it now, I am challenged for a password. Is this a Shutter Encoder prompt or is youtube-dl prompting for a password? 

Shutter Encoder 18.4 running on macOS 14.6.1 on M2 Max Apple Silicon.

<img width="505" alt="Screenshot 2024-09-11 at 9 15 58 PM" src="https://github.com/user-attachments/assets/9da4e1d3-fa0c-4e37-8b98-634d73678923">

**Comment by paulpacifico** [comment]
Yes because the latest version (v18.4) is now officially signed, BUT if I sign yt-dlp, it no longer works so it has to be downloaded separately and Shutter Encoder asking the password to make it executable.

I was able to make the download of yt-dlp during the installation process for the next release (v18.5) so it should not be asked again.

Paul.

**Comment by ConnieVic** [comment]
Thank you for the prompt response. I eagerly await the release of v18.5.
