### ISSUE TITLE
[feature] Repeat detection

### ISSUE THREAD

**Issue by chenlung** [paulpacifico/shutter-encoder#25]
In the Analysis section, a 'Repeat detection' function would be useful to find consecutive frames that are the same.

**Comment by paulpacifico** [comment]
Great idea! I have to check how to do that with FFmpeg.
Thanks,
Paul.

**Comment by chenlung** [comment]
As well as duplicate frames, duplicate _sections_ (e.g. the same five seconds found elsewhere in the film) would be interesting.

**Comment by melmatsuoka** [comment]
I noticed that the "Remove duplicate frames" option in "Advanced Features" is only available when encoding to one of the "Output Formats", and not with any of the "Editing Codecs". Would it be possible to add this option to the Editing codec options? I have a Bash script which de-dupes video files using the mpdecimate filter as well, and it works fine when writing to ProRes. It would be great if I could also use Shutter Encoder for this same task.

**Comment by paulpacifico** [comment]
@melmatsuoka This is strange because by removing the duplicated frames, you're getting a **V**ariable **F**rame **R**ate output which is not possible with editing codec or I am wrong? I will check this.
Paul.

**Comment by melmatsuoka** [comment]
> @melmatsuoka This is strange because by removing the duplicated frames, you're getting a **V**ariable **F**rame **R**ate output which is not possible with editing codec or I am wrong? I will check this.
> 
> Paul.

#The typical scenario which I'd use it for is removing dupe frames from an improperly frame-rate converted video. The most common mistake is when someone drops a 23.98 FPS clip into a 29.97 editing timeline, then exports it out to a new ProRes file. Most editing apps will apply "progressive pull down" to the exported clip in order to maintain the real-time playback of the clip when exported to 29.97. in cases like this, removing the duplicate frames will restore the one-to-one 23.98 cadence of the original clip, in the same way that a reverse telecine operation restores 23.98/24p from an interlaced 29.97 clip with 3:2 pulldown in it.

The mpdecimate docs actually refers to this scenario as one of the useful applications of mpdecimate.

In cases where a standard frame rate (e.g. 23.98 or 24) cannot be automatically inferred from the de-duped frames, you could perhaps allow the user to force conform the playback timebase of the deduped clip to a frame rate of their choosing. For VFX/rotoscoping workflows, this would be particularly useful, since you never want to roto the same frame twice, regardless of the frame rate!

**Comment by chenlung** [comment]
I'm told that [MSU VQMT's Drop Frames metric](http://www.compression.ru/video/quality_measure/metric_plugins/dfm_en.htm) can do this.

**Comment by chenlung** [comment]
'Remove duplicate frames' was implemented in 14.3 (not sure how I missed that).

It would be very useful to have a report generated which details the timecodes.

**Comment by chenlung** [comment]
Perhaps it's [freezedetect](https://ffmpeg.org/ffprobe-all.html#freezedetect)?

Shutter removes them, but I don't know what it uses for that. I'm only interested in analysis; hopefully the aforementioned function from ffprobe works similarly in detection (I wonder if settings are needed?).
