### ISSUE TITLE
[REQ] Intel oneAPI Video Processing Library support

### ISSUE THREAD

**Issue by forart** [paulpacifico/shutter-encoder#59]
We noticed that from 1.5.0 release, Handbrake uses "Updated Intel Quick Sync to use the Intel oneAPI Video Processing Library (oneVPL)".

...do you think could be useful to support it in SE ?

https://github.com/oneapi-src/oneVPL
https://github.com/oneapi-src/oneVPL-intel-gpu

Hope that helps/inspires.

**Comment by paulpacifico** [comment]
Thanks for your feedback, I've did some research and I have no real answer...

It seems FFmpeg (backend tool for Shutter Encoder) add it since 2021/10/15: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20211015133915.13624-11-haihao.xiang@intel.com/

But it does not figure out into the configure options: https://github.com/FFmpeg/FFmpeg/blob/master/configure

Moreover, on Hardware/Quicksync page of FFmpeg: https://trac.ffmpeg.org/wiki/Hardware/QuickSync
It shows: 
**Build FFmpeg with oneVPL
coming soon**

Maybe it's automatically enable for the new releases of FFmpeg. I'm always compiling with git sources for SE builds BTW.

Paul.
