### ISSUE TITLE
[Request] Shutter Encoder flatpak version

### ISSUE THREAD

**Issue by hulores** [paulpacifico/shutter-encoder#98]
Hi, would like to know if Shutter Encoder could be added to Flathub? It would be wonderful to to  install into any distro that is currently not supported (Clear Linux, Fedora or Arch linux for example).

**Comment by Radium-bit** [comment]
> Hi, would like to know if Shutter Encoder could be added to Flathub? It would be wonderful to to install into any distro that is currently not supported (Clear Linux, Fedora or Arch linux for example).

Shutter Encoder had a Appimage release pack, you can download the Appimage file and execute it directly on any Linux distribution.

**Comment by flexagoon** [comment]
I'd also love to have a Flatpak version

**Comment by flexagoon** [comment]
@paulpacifico why was this closed? There's still no Flatpak version as far as I can tell

**Comment by pobthebuilder** [comment]
started a Flatpak build of Shutter Encoder here.
https://github.com/pobthebuilder/shutter-encoder-flatpak
this is very useful for people on fedora silverblue.

**Comment by IkelAtomig** [comment]
@paulpacifico - I think you could use the scripts by @pobthebuilder and use it to automate Flaptak builds for release.

**Comment by TheRealFame** [comment]
After a bit of time, Sadly there is still no flakpak version, or automated flatpak version.

**Comment by IkelAtomig** [comment]
I don't think @paulpacifico is interested on linux side.

**Comment by IkelAtomig** [comment]
My best bet is to use a distrobox debian container problem is there is no repo.

**Comment by pobthebuilder** [comment]
after not having much time for linux for a while, i'm pivoting back to linux as my daily driver and dedicating more time to video stuff. therefore i've just submitted a huge chunk of updates to the shutter encoder flatpak to bring it up to date and make it much closer to the appimage version.

@paulpacifico i'd like to volunteer to collaborate with you and maintain a flatpak version of shutter encoder? i'd propose to submit my version to flathub to make it available to all flatpak users. happy to make whatever changes you would like to make and work with you to make sure it meets your standards.

would you be amenable to this?

**Comment by paulpacifico** [comment]
Hi @pobthebuilder 

Sorry for the delay, I was on holiday.

I really happy if you can help me on Linux because I'm not familiar with and I have no time left to develop more package.

I will be 100% available since the 15 November to develop more Shutter Encoder.

What kind of files you need for the flatpak version?

Thank you very much,
Paul.

**Comment by pobthebuilder** [comment]
i don't really need anything at all, just your permission. if you check out the repo here:
https://github.com/pobthebuilder/shutter-encoder-flatpak

i'm already building a flatpak version of shutter encoder. 

i'd like to submit this to flathub:
https://flathub.org/
which is the "app store" for flatpak applications that's widely used by fedora and redhat.

if you see any concerns with the flatpak version submitted to flathub; i'm more than happy for you to forward them directly back to the flatpak repo here:
https://github.com/pobthebuilder/shutter-encoder-flatpak

that's it really! if you're happy, i'll try and go ahead and submit my flatpak version of shutter encoder to flathub. this will make it MUCH easier for redhat/fedora/silverblue users to consume shutter encoder!

**Comment by paulpacifico** [comment]
That's seems perfect! You have all my permission, I'm really grateful because I have no time to do that so that's a huge help for me.

I'm working on the v18.6 currently.

Paul.

**Comment by thibaultmol** [comment]
Would be nice to then get the app verified as well if that's possible: https://docs.flathub.org/docs/for-users/verification/

Honestly in general, it would be nice if this flatpak version is then also linked in your readme and websites. Because appimage... is really not the format that most linux users care about, it's flatpak and native package

**Comment by caminashell** [comment]
@pobthebuilder @paulpacifico 
What is the status of this being verified by Flathub, please?

**Comment by Sturmlocke86** [comment]
I just asked about this as well: https://www.reddit.com/r/shutterencoder/comments/1jjo5nq/flatpak/

I'd love to see this on Flathub because that's the number 1 source for Linux apps these days and I only found out about this good app by sheer coincidence while browsing the web. I also think official verification would be good too so that ppl know it's coming from an official and trusted source. Thanks!

**Comment by teohhanhui** [comment]
@pobthebuilder

https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md#submitting-a-new-package
https://docs.flathub.org/docs/for-app-authors/submission
